#!/usr/bin/env python
import pygame
from pygame.locals import *

pygame.init()

frame = pygame.Surface((320,240))

DISPLAY = pygame.display.set_mode((320,240),HWSURFACE|DOUBLEBUF)

vm = pygame.image.load("viewmodel.png")
l = pygame.image.load("testlevel.png")
pygame.display.set_caption("PseudoCasting Demo - 2.0 - Sam Tubb")

def generateView(pos,level):
    #Generate Color
    colors0=[[pos[0]-2,pos[1]-5],[pos[0]-2,pos[1]-4],[pos[0]-2,pos[1]-3],[pos[0]-2,pos[1]-2]]
    colors1=[[pos[0]-1,pos[1]-5],[pos[0]-1,pos[1]-4],[pos[0]-1,pos[1]-3],[pos[0]-1,pos[1]-2],[pos[0]-1,pos[1]-1]]
    colors2=[[pos[0],pos[1]-5],[pos[0],pos[1]-4],[pos[0],pos[1]-3],[pos[0],pos[1]-2],[pos[0],pos[1]-1]]
    colors3=[[pos[0]+1,pos[1]-5],[pos[0]+1,pos[1]-4],[pos[0]+1,pos[1]-3],[pos[0]+1,pos[1]-2],[pos[0]+1,pos[1]-1]]
    colors4=[[pos[0]+2,pos[1]-5],[pos[0]+2,pos[1]-4],[pos[0]+2,pos[1]-3],[pos[0]+2,pos[1]-2]]

    #Draw the View
    #0,0
    pygame.draw.polygon(frame, (level.get_at(colors0[0])), [(0,33),(0,43),(70,43),(76,33)], 0)
    #0,1
    pygame.draw.polygon(frame, (level.get_at(colors0[1])), [(0,45),(0,68),(53,68),(68,45)], 0)
    #0,2
    pygame.draw.polygon(frame, (level.get_at(colors0[2])), [(0,70),(0,119),(19,119),(51,70)], 0)
    #0,3
    pygame.draw.polygon(frame, (level.get_at(colors0[3])), [(0,121),(0,147),(17,121)], 0)

    #1,0
    pygame.draw.polygon(frame, (level.get_at(colors1[0])), [(78,33),(72,43),(126,43),(129,33)], 0)
    #1,1
    pygame.draw.polygon(frame, (level.get_at(colors1[1])), [(70,45),(55,68),(119,68),(126,45)], 0)
    #1,2
    pygame.draw.polygon(frame, (level.get_at(colors1[2])), [(53,70),(21,119),(106,119),(119,70)], 0)
    #1,3
    pygame.draw.polygon(frame, (level.get_at(colors1[3])), [(19,121),(0,149),(0,197),(84,197),(105,121)], 0)
    #1,4
    pygame.draw.polygon(frame, (level.get_at(colors1[4])), [(0,199),(0,239),(73,239),(84,199)], 0)

    #2,0
    pygame.draw.polygon(frame, (level.get_at(colors2[0])), [(131,33),(128,43),(180,43),(177,33)], 0)
    #2,1
    pygame.draw.polygon(frame, (level.get_at(colors2[1])), [(128,45),(121,68),(186,68),(180,45)], 0)
    #2,2
    pygame.draw.polygon(frame, (level.get_at(colors2[2])), [(121,70),(108,119),(199,119),(186,70)], 0)
    #2,3
    pygame.draw.polygon(frame, (level.get_at(colors2[3])), [(107,121),(86,197),(219,197),(199,121)], 0)
    #2,4
    pygame.draw.polygon(frame, (level.get_at(colors2[4])), [(86,199),(75,239),(230,239),(219,199)], 0)

    #3,0
    pygame.draw.polygon(frame, (level.get_at(colors3[0])), [(179,33),(182,43),(234,43),(226,33)], 0)
    #3,1
    pygame.draw.polygon(frame, (level.get_at(colors3[1])), [(182,45),(188,68),(253,68),(235,45)], 0)
    #3,2
    pygame.draw.polygon(frame, (level.get_at(colors3[2])), [(188,70),(201,119),(293,119),(255,70)], 0)
    #3,3
    pygame.draw.polygon(frame, (level.get_at(colors3[3])), [(201,121),(221,197),(319,197),(319,153),(294,121)], 0)
    #3,4
    pygame.draw.polygon(frame, (level.get_at(colors3[4])), [(221,199),(232,239),(319,239),(319,199)], 0)

    #4,0
    pygame.draw.polygon(frame, (level.get_at(colors4[0])), [(228,33),(236,43),(319,43),(319,33)], 0)
    #4,1
    pygame.draw.polygon(frame, (level.get_at(colors4[1])), [(237,45),(255,68),(319,68),(319,45)], 0)
    #4,2
    pygame.draw.polygon(frame, (level.get_at(colors4[2])), [(257,70),(295,119),(319,119),(319,70)], 0)
    #4,3
    pygame.draw.polygon(frame, (level.get_at(colors4[3])), [(296,121),(319,150),(319,121)], 0)

go = True

playerPos=[15,15]
frame.fill((150,150,150))
generateView(playerPos,l)
while go:
    DISPLAY.blit(frame,(0,0))
    pygame.display.flip()
    for e in pygame.event.get():
        if e.type == QUIT:
            go = False
            pygame.display.quit()
        if e.type == KEYDOWN:
            if e.key == K_F5:
                pygame.display.toggle_fullscreen()
            if e.key == K_UP:
                playerPos[1]-=1
            if e.key == K_DOWN:
                playerPos[1]+=1
            if e.key == K_LEFT:
                playerPos[0]-=1
            if e.key == K_RIGHT:
                playerPos[0]+=1
            frame.fill((150,150,150))
            generateView(playerPos,l)

exit()
